### ISSUE TITLE
Testing sometimes hangs

### ISSUE THREAD

**Issue by sergefdrv** [filecoin-project/mir#36]
Sometimes `make test` hangs, e.g. [here](https://github.com/filecoin-project/mir/runs/6215449350).

**Comment by sergefdrv** [comment]
I managed to reproduce it with (normally it takes around 30s for testing on my machine):

```sh
while GOFLAGS="-timeout=1m -count=1" go version && make test; do :; done
```

**Comment by matejpavlovic** [comment]
I think I got it.
The transport layer is writing messages that it receives over the network to a channel, from which the node implementation reads them. When the node is shutting down, it stops reading incoming messages from this channel. However, if there are still incoming messages on the wire at that time, the transport layer tries to write them to the channel and blocks (since nobody reads any more), preventing a clean shutdown of the transport layer. Should not be hard to fix using a Context for the transport layer.
