### ISSUE TITLE
Incoming messages for garbage-collected submodules may fill the message buffer

### ISSUE THREAD

**Issue by xosmig** [filecoin-project/mir#368]
As far as I understand the implementation in [pkg/factorymodule/factory.go](https://github.com/filecoin-project/mir/blob/main/pkg/factorymodule/factory.go), incoming network messages destined for non-existing modules are buffered within a limit and are dropped once the limit is exceeded.

One issue here is that the implementation does not seem to distinguish between the modules that have not yet been created and the modules that have already been garbage-collected.
Hence, even in absence of malicious nodes and with a relatively synchronous network, the message buffer may get full of messages destined for old, garbage-collected, submodules.

**Suggested solutions:**
1. (infinite memory, no API changes) Remember the list of garbage-collected module IDs;
2. (finite memory, small API change) require the submodule IDs to end with ":XX", where XX is the retention index.

**Comment by matejpavlovic** [comment]
I thought about this too, but I concluded it is not an issue, because the buffer eviction policy.
When it runs out of space, it starts dropping the least recently added messages.
The only reason for which the buffer can reject an incoming message directly is when that single message is larger than the whole buffer space.

This is the implementation: https://github.com/filecoin-project/mir/blob/dc5675efdd7e9405f6c9c29d86ee80ab4912a705/pkg/messagebuffer/messagebuffer.go#L141-L146

The current implementation is still sub-optimal in the corner case where the incoming message actually is bigger than the whole buffer, as it has the side effect of removing all the older messages, but still rejects the incoming one. This could be easily fixed by simply checking for that particular case.

**Comment by matejpavlovic** [comment]
Including the retention index in the module ID is also a viable solution that I considered, but in the end I decided against it, as it adds complexity to the API and the solution with the FIFO buffer works. That said, I'm not strongly against including the retention index (it is often natural to include it anyway), but I'd prefer avoiding it until it's necessary.
