### ISSUE TITLE
Unsafe error handling

### ISSUE THREAD

**Issue by dnkolegov** [filecoin-project/mir#39]
There are many places the code panic (examples, non-exhaustive list):
 - https://github.com/filecoin-project/mir/blob/9bad9a7747a5747e7c0f5adcf9e1fb38cd3000c9/pkg/clients/dummyclienttracker.go#L54
- https://github.com/filecoin-project/mir/blob/9bad9a7747a5747e7c0f5adcf9e1fb38cd3000c9/pkg/iss/bucket.go#L156
- https://github.com/filecoin-project/mir/blob/2fa16dc77fdf4c946d79ddb26d8ed0b686e4fd4c/pkg/iss/iss.go#L318

We should define an error handling policy, considering the panic categories and panic recovery mechanisms.

**Comment by matejpavlovic** [comment]
Good point Denis. I did think about this and error handling is implemented at Node level through the WorkErrorNotifier (adapted from the original implementation). In a nutshell, if the Protocol module panics, the code that is performing the actual execution catches the panic and returns an error saying "Protocol implementation panicked (because XYZ)". Note that this is unavoidable in any case, since the protocol implementation is, in some cases, supposed to be provided by the user (of Mir) and we thus need to count on it panicking any time. But a panic in the protocol can only ever occur due to a bug in the implementation, never due to malicious input. The protocol must ensure that. The lines you linked cannot be reached unless there is a bug in the implementation.

That being said, the current implementation of ISS is still ongoing and not all inputs are properly sanitized yet. I can imagine that at this stage the protocol could be made to panic by sending it a maliciously crafted message. This should not be the case for a final implementation.
