### ISSUE TITLE
Proto-tagged maps and slices do not tolerate nil values

### ISSUE THREAD

**Issue by ranchalp** [filecoin-project/mir#401]
Struct fields of a proto message that are maps or slices and tagged (`mir.key_type` and `mir.value_type` for maps, or `mir.type` for the inner type of the slice) do not tolerate nil values.

A similar behaviour occurs the methods `...FromPb` (from the generated `types.mir.go`) on slices and certs whose content is empty.

**Comment by ranchalp** [comment]
In general, we should not use nil pointers as zero values.

**Comment by matejpavlovic** [comment]
It can become very inconvenient to not be able to use `nil` in the generated data structures. For instance, when writing tests we might need to use a message without specifying a very concrete one. However, a `nil` value for the content cannot be used right now. Instead of constructing a `Message` object with `nil` content, we need to use some (arbitrary) very concrete message (e.g., a PBFT prepare message) or define a special simple message type, specifically for testing.

Thus, I think that instead of not using `nil` values, we should update the code generation tool to support nil values.

**Comment by ranchalp** [comment]
Agreed, it still holds that, in general, we should not use nil pointers as zero values, but the code generation tool should support nil values.
