### ISSUE TITLE
Pulling missing transactions in availability module

### ISSUE THREAD

**Issue by matejpavlovic** [filecoin-project/mir#411]
Investigate whether this is indeed not implemented and implement it if necessary.

https://github.com/filecoin-project/mir/blob/c716023aa29e4efb7c46a753507e531d33c66090/protos/availabilitypb/mscpb/mscpb.proto#L59-L68

Is that code obsolete in favor of this one?
https://github.com/filecoin-project/mir/blob/c716023aa29e4efb7c46a753507e531d33c66090/protos/availabilitypb/mscpb/mscpb.proto#L44-L57

**Comment by matejpavlovic** [comment]
@xosmig could you confirm this? From looking at [batchreconstruction.go](https://github.com/filecoin-project/mir/blob/1872c987bd6f6ad4a3648a71691c5ff8ffd363b4/pkg/availability/multisigcollector/parts/batchreconstruction/batchreconstruction.go), it seems to me that the answer is yes, just want to double-check.

**Comment by xosmig** [comment]
I don't remember exactly, but I think the difference is in granularity. Perhaps, we wanted to capitalize on the fact that the nodes get transactions from the same mempool and implement an optimization where, instead of sending a batch of transactions from node A to node B, we would send a batch of *transctions ids* from A to B and would let node B request from A only transactions that it doesn't have in its mempool.

**Comment by xosmig** [comment]
I guess, theoretically, you could go further and send only some digest of the set of ids instead of the set itself.
Here's a potentially relevant paper: https://www.ics.uci.edu/~eppstein/pubs/EppGooUye-SIGCOMM-11.pdf

**Comment by matejpavlovic** [comment]
Ah I see, I didn't realize this probably was the purpose. Yes, that optimization has been on the table basically since the start, it just never has been high enough on the priority list.

I opened this issue only to make sure that this is not related to the correctness of the current implementation. I'm closing it and let's deal with the optimization separately.

And thanks for the pointer to the paper!
