### ISSUE TITLE
Breaking changes in crypto library (G1 curve problem)

### ISSUE THREAD

**Issue by matejpavlovic** [filecoin-project/mir#467]
More info here: https://github.com/drand/kyber-bls12381/releases/tag/v0.3.0

Code that uses it:
https://github.com/filecoin-project/mir/blob/e7b06cb0f1094407cc861e3ddd16c5280601c1c2/pkg/threshcrypto/tbls.go#L36-L43

**Comment by abread** [comment]
Luckily, the only breakage here is incompatibility with keys/signatures generated with the old version (at least I expect them to be incompatible).   This shouldn't be a problem since `threshcrypto` is currently only being used in my fork as far as I know.

By updating to 0.3.0, we will simply start using the correct DSTs, which are the new default.
I'll open a PR to leave it ready for merge.
